margin = 120
always_for_in = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
short_to_long_function_def = true
long_to_short_function_def = false
conditional_to_if = true
normalize_line_endings = "unix"
trailing_comma = false
indent_submodule = true
separate_kwargs_with_semicolon = true
short_circuit_to_if = true
disallow_single_arg_nesting = true
